<?php include 'config.php' ?>
<!DOCTYPE HTML>
<html lang="en" xmlns:fb="http://ogp.me/ns/fb#">
    <head>
        <?php $title = "Privacy Policy - Open Knowledge Maps"; ?>
        <?php include($COMPONENTS_PATH . 'head_bootstrap.php'); ?>
        <?php include($COMPONENTS_PATH . 'head_standard.php'); ?>
    </head>
    <body id="privacy-page">



        <?php include($COMPONENTS_PATH . 'header.php'); ?>


        <div id="imprint">
            <h2>Privacy Policy</h2>
            <p style="max-width:600px; margin:0px auto;">
                <br>
                <span class="bold">Analysis service</span> 
                <br>Our website uses Piwik, a web analysis service which uses cookies (text files that are stored on your computer and allow us to analyse the use of our website). For this purpose, the usage information generated by the cookie (including your truncated IP address) is transferred to our server and stored for the purpose of analysing the use of our website, which in turn allows us to optimise the website accordingly. In this process, your IP address is anonymised immediately in order to ensure your anonymity as a user. The site usage information generated by the cookie is not passed on to third parties. You can block the use of cookies in your browser settings; however, you may not be able to use all of the functions offered on this website as a result.
                <br><br>
                If you do not consent to the storage and analysis of data on your visit to our website, you can block these actions at any time by clicking below. In such a case, an opt-out cookie will be stored on your device, meaning that Piwik will not collect session data from your visit.
                <br>
                <i>Note:</i> If you delete your cookies, your opt-out cookie will also be deleted, meaning that you will have to reactivate the cookie for your next visit to the site.
                <br><br>
                <span class="bold">Opt-out</span>
                <br>
                <iframe style="border: 0; width: 600px; font-family: 'Open Sans';" src="https://openknowledgemaps.org/piwik_stats/index.php?module=CoreAdminHome&action=optOut&language=en"></iframe>
            
                
                <span class="bold">"Addthis" Bookmarking Tool</span>
                <br>
                This website contains "Addthis" plugins, which enable you to place bookmarks or share interesting contents of the website. "Addthis" uses cookies. 
                The files thus created (such as the time of usage or the browser language) are passed on to the Add This LLC in the USA and are processed there. For more information on data processing by Add This LLC and the data protection provided by Add This LLC, please go to <a href="www.addthis.com/privacy" target="_blank" class="underline">www.addthis.com/privacy</a>.
                <br><br>
                This website contains specific information about the type of processed data and their purpose. We do not process this data. By using the "Addthis" field you consent to data processing by Add This LLC to the extent specified on the web page of <a href="www.addthis.com" target="_blank" class="underline">www.addthis.com</a>. 
                You may withdraw your consent to the processing of your data at any time by the use of a  "Opt-Out cookie" that you can download here: <a href="www.addthis.com/privacy/opt-out" target="_blank" class="underline">www.addthis.com/privacy/opt-out</a>

            
            </p>
            





        </div>
        <?php include($COMPONENTS_PATH . 'footer.php'); ?>