<?php include 'config.php' ?>
<!DOCTYPE HTML>
<html lang="en" xmlns:fb="http://ogp.me/ns/fb#">
    <head>
        <?php $title = "Privacy Policy - Open Knowledge Maps"; ?>
        <?php include($COMPONENTS_PATH . 'head_bootstrap.php'); ?>
        <?php include($COMPONENTS_PATH . 'head_standard.php'); ?>
    </head>
    <body>



        <?php include($COMPONENTS_PATH . 'header.php'); ?>


        <div id="imprint">
            <h2>Privacy Policy</h2>
            <p style="max-width:600px; margin:0px auto;">
                <br>
                <span class="bold">Analysis service</span> 
                <br>Our website uses Piwik, a web analysis service which uses cookies (text files that are stored on your computer and allow us to analyse the use of our website). For this purpose, the usage information generated by the cookie (including your truncated IP address) is transferred to our server and stored for the purpose of analysing the use of our website, which in turn allows us to optimise the website accordingly. In this process, your IP address is anonymised immediately in order to ensure your anonymity as a user. The site usage information generated by the cookie is not passed on to third parties. You can block the use of cookies in your browser settings; however, you may not be able to use all of the functions offered on this website as a result.
                <br><br>
                If you do not consent to the storage and analysis of data on your visit to our website, you can block these actions at any time by clicking below. In such a case, an opt-out cookie will be stored on your device, meaning that Piwik will not collect session data from your visit.
                <br>
                <i>Note:</i> If you delete your cookies, your opt-out cookie will also be deleted, meaning that you will have to reactivate the cookie for your next visit to the site.
                <br><br>
                <span class="bold">Opt-out</span>
                <br>
                <iframe style="border: 0; height: 200px; width: 600px;" src="https://openknowledgemaps.org/piwik_stats/index.php?module=CoreAdminHome&action=optOut&language=en"></iframe>
            </p>
        </div>
        <?php include($COMPONENTS_PATH . 'footer.php'); ?>